apiVersion: v1
kind: Service
metadata:
  name: webapp-signin
  namespace: demo
  labels:
    app.kubernetes.io/name: webapp-signin
    kubernetes.azure.com/generator: draft
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: webapp-signin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80